### ISSUE TITLE
feat: add collaborator card component

### ISSUE THREAD

**Issue by AfonsoMartins26** [cesium/hydrogen#24]
![Captura de ecrã 2024-09-22 220140](https://github.com/user-attachments/assets/97c865ce-bee7-4b28-8457-300385f0361c)
![Captura de ecrã 2024-09-22 230225](https://github.com/user-attachments/assets/5b6ab9a3-5037-4dd2-a934-00d7a9a2a255)

**Comment by diogogmatos** [comment]
Done ✅
